const products = [
    {
        id: 1,
        title: "Street Finest V1 Sweatshirt",
        price: 850.00,
        image: "D:\\1st Year\\itc website\\products\\p3.webp",
        description: "'The Brand You Can Brag About' Clean, bold, and unmistakable. This piece features our signature Street Finest speed-font logo in a striking orange and yellow gradient on a crisp white oversized tee.",
        sizes: ["XS", "S", "M", "L", "XL"],
    },
    {
        id: 2,
        title: "Street Finest V2 Sweatshirt",
        price: 850.00,
        image: "D:\\1st Year\\itc website\\products\\p4.webp",
        description: "'Street Finest V2 Sweatshirt' updated design with the classic speed-font logo in orange and yellow gradient on a bold white sweatshirt.",
        sizes: ["XS", "S", "M", "L", "XL"],
    },
    {
        id: 3,
        title: "Street Finest V3 Sweatshirt",
        price: 850.00,
        image: "D:\\1st Year\\itc website\\products\\p2.webp",
        description: "'Street Finest V3 Sweatshirt' premium sweatshirt with signature bold logo and modern streetwear style.",
        sizes: ["XS", "S", "M", "L", "XL"],
    },
    {
        id: 4,
        title: "Street Finest Classic White Shirt",
        price: 550.00,
        image: "D:\\1st Year\\itc website\\products\\p1.webp",
        description: "'Classic White Shirt' simple, clean, and stylish with Street Finest branding.",
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 5,
        title: "Street Finest 'Made With Love' Shirt",
        price: 550.00,
        image: "D:\\1st Year\\itc website\\products\\p5.webp",
        description: "'Made With Love' shirt features bold statement graphics and comfortable fit.",
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 6,
        title: "Street Finest 'You Only Talk About It' Shirt",
        price: 550.00,
        image: "D:\\1st Year\\itc website\\products\\p6.webp",
        description: "'You Only Talk About It' shirt inspired by street vibes, bold graphic, and comfy cotton.",
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 7,
        title: "Street Finest Classic Shirt V2",
        price: 550.00,
        image: "D:\\1st Year\\itc website\\products\\p7.webp",
        description: "'Classic Shirt V2' sleek, street-ready design, perfect for casual everyday wear.",
        sizes: ["S", "M", "L", "XL"],
    },
    {
        id: 8,
        title: "Street Finest 'Me, Yosi, Coffee, And Music The World' Shirt",
        price: 550.00,
        image: "D:\\1st Year\\itc website\\products\\p8.webp",
        description: "'Me, Yosi, Coffee, And Music The World' shirt featuring bold typography and relaxed fit.",
        sizes: ["S", "M", "L", "XL"],
    }
];
